use Test::More skip_all => "Not fully implemented yet.";

# https://bitbucket.org/pstatic/pubsubhubbub/src/f650addc29aa/test_pubsubhubbub.py


my $post =<<'EOPOST';
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:feedburner="http://rssnamespace.org/feedburner/ext/1.0"><channel><title>Boing Boing</title><link>http://boingboing.net</link><atom10:link type="application/rss+xml" href="http://feeds.boingboing.net/boingboing/iBag" xmlns:atom10="http://www.w3.org/2005/Atom" rel="self"/><description>Brain candy for Happy Mutants</description><language>en</language><lastBuildDate>Sun, 02 Oct 2011 15:17:30 PDT</lastBuildDate><generator>http://wordpress.org/?v=3.2.1</generator><sy:updatePeriod xmlns:sy="http://purl.org/rss/1.0/modules/syndication/">hourly</sy:updatePeriod><sy:updateFrequency xmlns:sy="http://purl.org/rss/1.0/modules/syndication/">1</sy:updateFrequency><atom10:link type="application/rss+xml" href="http://feeds.boingboing.net/boingboing/iBag" xmlns:atom10="http://www.w3.org/2005/Atom" rel="self"/><feedburner:info uri="boingboing/ibag"/><atom10:link href="http://pubsubhubbub.appspot.com/" xmlns:atom10="http://www.w3.org/2005/Atom" rel="hub"/><image><link>http://boingboing.net</link><url>http://boingboing.net/icons/bb144.jpg</url><title>Boing Boing</title></image><feedburner:browserFriendly>This is an XML content feed. It is intended to be viewed in a newsreader or syndicated to another site.</feedburner:browserFriendly>

<item><title>Occupy Wall Street: "Declaration of the Occupation of New York City"</title><link>http://feeds.boingboing.net/~r/boingboing/iBag/~3/s-YaFO94zSk/occupy-wall-street-declaration-of-the-occupation-of-new-york-city.html</link><category>Post</category><category>occupy wall steet</category><category>ows</category><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Xeni Jardin</dc:creator><pubDate>Sun, 02 Oct 2011 15:15:50 PDT</pubDate><guid isPermaLink="false">http://boingboing.net/?p=121426</guid><content:encoded xmlns:content="http://purl.org/rss/1.0/modules/content/">&lt;p&gt;A manifesto of sorts has emerged from &lt;em&gt;Occupy Wall Street&lt;/em&gt;: 
&lt;blockquote&gt;
&lt;p&gt;As we gather together in solidarity to express a feeling of mass injustice, we must notÂ lose sight of what brought us together. We write so that all people who feel wronged byÂ the corporate forces of the world can know that we are your allies.&lt;/p&gt;&lt;p&gt;
As one people, united, we acknowledge the reality: that the future of the human race requires the cooperation of its members; that our system must protect our rights, and upon corruption of that system, it is up to the individuals to protect their own rights, and those of their neighbors; that a democratic government derives its just power from the people, but corporations do not seek consent to extract wealth from the people and the Earth; and that no true democracy is attainable when the process is determined by economic power. We come to you at a time when corporations, which place profit over people, self-interest over justice, and oppression over equality, run our governments. We have peaceably assembled here, as is our right, to let these facts be known.&lt;p&gt;&lt;/blockquote&gt;
&lt;p&gt;Read: &lt;a href='http://nycga.cc/2011/09/30/declaration-of-the-occupation-of-new-york-city/'&gt;Declaration of the Occupation of New York City | NYC General Assembly&lt;/a&gt;.&lt;/p&gt;&lt;br clear="both" style="clear: both;"/&gt;
&lt;br clear="both" style="clear: both;"/&gt;
&lt;a href="http://ads.pheedo.com/click.phdo?s=bb7963a5a89f926b3b18cc0864d0c46b&amp;p=1"&gt;&lt;img alt="" style="border: 0;" border="0" src="http://ads.pheedo.com/img.phdo?s=bb7963a5a89f926b3b18cc0864d0c46b&amp;p=1"/&gt;&lt;/a&gt;
&lt;img alt="" height="0" width="0" border="0" style="display:none" src="http://segment-pixel.invitemedia.com/pixel?code=TechCons&amp;partnerID=167&amp;key=segment"/&gt;&lt;img alt="" height="0" width="0" border="0" style="display:none" src="http://pixel.quantserve.com/pixel/p-8bUhLiluj0fAw.gif?labels=pub.28925.rss.TechCons.7604,cat.TechCons.rss"/&gt;&lt;img alt="" height="0" width="0" border="0" style="display:none" src="http://amch.questionmarket.com/adsc/d887846/17/909940/adscout.php"/&gt;&lt;img src="http://feeds.feedburner.com/~r/boingboing/iBag/~4/s-YaFO94zSk" height="1" width="1"/&gt;</content:encoded><description>A manifesto of sorts has emerged from Occupy Wall Street: As we gather together in solidarity to express a feeling of mass injustice, we must notÂ lose sight of what brought us together. We write so that all people who feel wronged byÂ the corporate forces of the world can know that we are your allies. As [...]&lt;br clear="both" style="clear: both;"/&gt;
&lt;br clear="both" style="clear: both;"/&gt;
&lt;a href="http://ads.pheedo.com/click.phdo?s=bb7963a5a89f926b3b18cc0864d0c46b&amp;p=1"&gt;&lt;img alt="" style="border: 0;" border="0" src="http://ads.pheedo.com/img.phdo?s=bb7963a5a89f926b3b18cc0864d0c46b&amp;p=1"/&gt;&lt;/a&gt;
&lt;img alt="" height="0" width="0" border="0" style="display:none" src="http://segment-pixel.invitemedia.com/pixel?code=TechCons&amp;partnerID=167&amp;key=segment"/&gt;&lt;img alt="" height="0" width="0" border="0" style="display:none" src="http://pixel.quantserve.com/pixel/p-8bUhLiluj0fAw.gif?labels=pub.28925.rss.TechCons.7604,cat.TechCons.rss"/&gt;&lt;img alt="" height="0" width="0" border="0" style="display:none" src="http://amch.questionmarket.com/adsc/d887846/17/909940/adscout.php"/&gt;</description><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://boingboing.net/2011/10/02/occupy-wall-street-declaration-of-the-occupation-of-new-york-city.html/feed</wfw:commentRss><slash:comments xmlns:slash="http://purl.org/rss/1.0/modules/slash/">0</slash:comments><feedburner:origLink>http://boingboing.net/2011/10/02/occupy-wall-street-declaration-of-the-occupation-of-new-york-city.html</feedburner:origLink></item>
</channel>
</rss>
EOPOST
